name: synchronize
description: This package provides synchronization implementations, including a Lock (with support for reentrancy), a ReaderWriterLock (with wupport for upgrades and downgrades), and a Semaphore.
version: 1.0.0
repository: https://github.com/d-markey/locking

environment:
  sdk: ^3.0.0

dependencies:
  cancelation_token: ^1.0.0
  using: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
