name: synchronize
description: This package provides synchronization implementations, including a (reentrant) Lock, a (upgradable) ReaderWriterLock, and a Semaphore.
version: 1.1.1
repository: https://github.com/d-markey/Synchronize

environment:
  sdk: ^3.0.0

dependencies:
  cancelation_token: ^1.1.0
  using: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
